sen = input("문장 입력: ")
print(f'#'*20)
print(f'대문자 변환: {sen.upper()}')
print(f'소문자 변환: {sen.lowerer()}')
print(f'문자열 길이: {len(sen)}')
print(f'공백으로 분리: {sen.split()}')
print(f'문자로 분리: {sen.split(",")}')
print(f'o의 위치: {sen.find('o')}')
print(f'o의 개수: {sen.count('o')}')
print(f'Python을 AI로 교체: {sen.replace()}')